# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/c-prav
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# for check logs
logging.level.com.c_prav.portal.config=DEBUG

# Okta OAuth2 Configuration
okta.oauth2.issuer=https://dev-53619571.okta.com/oauth2/default
okta.api.token=002p8uVbhVmEhPONCKNYb-9hBJ8RdDRtVfdL_BODwi
okta.api.url=https://dev-53619571.okta.com
